made changes to installer

diff --git a/install-dependencies b/install-dependencies
--- a/install-dependencies
+++ b/install-dependencies
@@ -1,11 +1,11 @@
-#! /usr/bin/bash
-#install script for the dotfiles
+#!/usr/bin/bash
 
-R='\033[0;31m'   #'0;31' is Red's ANSI color code
-G='\033[0;32m'   #'0;32' is Green's ANSI color code
-Y='\033[1;32m'   #'1;32' is Yellow's ANSI color code
-B='\033[0;34m'   #'0;34' is Blue's ANSI color code
-NC='\033[0m' # No Color
+# ANSI color codes
+R='\033[0;31m'  
+G='\033[0;32m'  
+Y='\033[1;32m'  
+B='\033[0;34m'  
+NC='\033[0m' 
 
 pause() {
   printf "${Y} Press any key to continue${NC}"
@@ -17,116 +17,87 @@ set -e
 printf "${R}# Hello there, looks like you want to yoink my dots. :D ${NC}\n"
 sleep 2
 
-HELPER="paru"
+# Select AUR helper using whiptail
+whiptail --title "Select AUR Helper" --yes-button "paru" --no-button "yay" --yesno "Choose your AUR helper" 10 50
+if [ $? -eq 0 ]; then
+    HELPER="paru"
+else
+    HELPER="yay"
+fi
+echo "Selected AUR helper: $HELPER"
 
+# Update system
 printf "${R}# Updating your system (sudo pacman -Syu)${NC}\n"
-echo 
 sudo pacman --noconfirm -Syu
-
 pause
 
+# Install libnewt
 printf "${R}# Installing libnewt on your system${NC}\n"
-echo
 sudo pacman -S --noconfirm libnewt
 pause
 
-printf "${R}# Installing base packages (base-devel, wget, git) ${NC}\n"
+# Install base packages
+printf "${R}# Installing base packages (base-devel, wget, git)${NC}\n"
 sudo pacman --noconfirm --needed -S base-devel wget git
+pause
 
-echo
-
-printf "${R} # Video driver${NC}"
-echo 
-
-# echo "1) xf86-video-intel 	2) xf86-video-amdgpu 3) nvidia 4) Skip"
-# read -r -p "Choose you video card driver(default 4)(will not re-install): " vid
-
-vid=$(whiptail --title "Graphics Driver" --menu "Choose a graphics driver for your system" 25 60 16 \
-             "xf86-video-intel" "Intel drivers" \
-             "xf86-video-amdgpu" "AMD drivers" \
-             "nvidia nvidia-settings nvidia-utils" "Nvidia drivers" \
-             "Skip" "No drivers" 3>&1 1>&2 2>&3 )
+# Video Driver Selection
+vid=$(whiptail --title "Graphics Driver" --menu "Choose a graphics driver for your system" 15 60 4 \
+    "xf86-video-intel" "Intel drivers" \
+    "xf86-video-amdgpu" "AMD drivers" \
+    "nvidia" "Nvidia drivers" \
+    "Skip" "No drivers" 3>&1 1>&2 2>&3)
 
 if [ "$vid" = "Skip" ]; then 
   vid="" 
-fi
-
-
-PACKAGES=$(for x in $(cat packagelist | sed  's/[ \t]*$//' | cut -d' ' -f1 ); do printf "$x " ; done)
-PKG_PROMPT=$(for x in $PACKAGES ; do printf "    - $x\n"; done)
-
-whiptail --title "Packages from standard repo" --yesno "The following packages will be installed would you like to proceed?\n$PKG_PROMPT" 25 75 
-
-exitstatus=$?
-
-exitstatus=$?
-if [ $exitstatus = 0 ]; then
-  echo "ok"
 else
-  echo "User canceled input."
+  printf "${R}# Installing video driver: $vid ${NC}\n"
+  sudo pacman --noconfirm --needed -S $vid
 fi
 
-sudo pacman -S --needed $PACKAGES
+pause
+
+# Confirm installation of standard repo packages
+PACKAGES=$(cat packagelist | sed 's/[ \t]*$//' | cut -d' ' -f1 | tr '\n' ' ')
+PKG_PROMPT=$(printf "    - %s\n" $PACKAGES)
+if whiptail --title "Packages from standard repo" --yesno "The following packages will be installed:\n$PKG_PROMPT\nWould you like to proceed?" 25 75; then
+  sudo pacman -S --noconfirm --needed $PACKAGES
+else
+  echo "User canceled the package installation."
+  exit 1
+fi
 
 pause
 clear
 
-# printf "${R} # Packages have been installed${NC}\n"
-# printf "${R} # AUR helper ${NC}\n"
-#
-#
-# printf "${Y}We need an AUR helper. It is essential. 1) paru       2) yay\nWhat is the AUR helper of your choice? (default is paru): ${NC}"
-# read -r num
-#
-# echo
-#
-# if [ $num -eq 2 ]
-# then
-#     HELPER="yay"
-# fi
-
-# Show a message that packages have been installed
-whiptail --title "Packages Installed" --msgbox "${R}Packages have been installed${NC}" 8 50
-
-# Display a yes/no style dialog with "yay" as "Yes" and "paru" as "No"
-whiptail --title "AUR Helper Selection" --yesno "${Y}Choose your AUR helper:${NC}\nYes -> yay\nNo -> paru" 10 60 --yes-button "yay" --no-button "paru"
-
-# Set the AUR helper based on the user's choice
-if [ $? -eq 0 ]; then
-    HELPER="yay"
-else
-    HELPER="paru"
+# Install AUR packages
+if ! command -v $HELPER &> /dev/null; then
+  echo "It seems that you don't have $HELPER installed, installing it now..."
+  git clone https://aur.archlinux.org/$HELPER.git ~/.srcs/$HELPER
+  (cd ~/.srcs/$HELPER/ && makepkg -si )
 fi
 
-# Echo the chosen AUR helper
-echo "Selected AUR helper: $HELPER"
-
-if ! command -v $HELPER &> /dev/null
-then
-  rm -rf ~/.srcs/$HELPER
-  echo "It seems that you don't have $HELPER installed, I'll install that for you before continuing."
-	git clone https://aur.archlinux.org/$HELPER.git ~/.srcs/$HELPER
-	(cd ~/.srcs/$HELPER/ && makepkg -si )
-fi
-
-AUR_PACKS="$(echo $(for x in $(cat packagelist-aur | sed  's/[ \t]*$//' | cut -d' ' -f1 ); do printf "$x " ; done))"
-
-
-# $HELPER --quiet -S rofi-greenclip i3lock-fancy-git ttf-jetbrains-mono cava rofi-bluetooth-git
+AUR_PACKS=$(cat packagelist-aur | sed 's/[ \t]*$//' | cut -d' ' -f1 | tr '\n' ' ')
 $HELPER --quiet -S $AUR_PACKS
 
 printf "${R} # All packages installed ${NC}\n"
-
 pause
 clear
 
-printf "${Y} Would you like to use fish as your default shell ${NC}? (Y/n)"
-read -r choice
+# Shell selection using whiptail
+if whiptail --title "Change Default Shell" --yesno "Would you like to use fish as your default shell?" 10 50; then
+  chsh -s /usr/bin/fish
+fi
 
-case "$choice" in
-  [Yy]) chsh -s /usr/bin/fish
-esac
+if whiptail --title "Stow Dotfiles" --yesno "Would you like to stow the dotfiles in your home directory?" 10 50; then
+  if [ -d "$HOME/dotfiles" ]; then
+    stow -d "$HOME/dotfiles" -t "$HOME" *
+    printf "${G}Dotfiles have been successfully stowed.${NC}\n"
+  else
+    printf "${R}The directory ~/dotfiles does not exist. Cannot stow dotfiles.${NC}\n"
+  fi
+else
+  printf "${Y}Skipping stowing of dotfiles.${NC}\n"
+fi
 
-echo
-
-printf "${Y} Would you like to install dotfiles t"
+echo "Dotfiles installation complete!"
